### ISSUE TITLE
Friendly DQ Column

### ISSUE THREAD

**Issue by gwenbeebe** [COHHIO/Rminor_elevated#58]
I've been playing around with icons as indicators lately, and my CoC loves it! This is very much a 'your mileage may vary' kind of thing, but I was thinking it could be fun to add in now that you're down to only two possibilities for data quality--with a key at the top to match the exact text you display now with the icons, of course.

I wish I'd thought of this earlier, it just occurred to me that it could be applied here when I was working on a document tracker today. Anyway, if you wanted to do it, it could look something like this:

![image](https://user-images.githubusercontent.com/43525277/117394692-7164bc80-aeab-11eb-8c16-dfcd4df308b0.png)

Let me know if you like it and want me to put in a PR for this! Or I can add it anywhere else you'd like to use icons, since I've got hours left.

**Comment by gwenbeebe** [comment]
It could also be fun for the Meets Objective column, since that's just a yes/no indicator

**Comment by kiadso** [comment]
(By confusing, I just mean putting a change like this out at this point in the timeline, not what the icons mean.)
